### PR TITLE
Fix a bug where 'toJSON' was producing a list

### LINKED ISSUE #7: Use objects for ToJSON/FromJSON instances
Currently records are converted into arrays of pairs:

```
> toJSON someRecord
Array [Array [String "author",String "Artyom"],Array [String "language",String "English"]]
```

Perhaps it would be better to convert them to objects instead? I understand that it would make conversions lossy if there are two fields with the same name, but I'm not sure how common that usecase it (in the worst case we could keep current `recToVal` under a different name, so that if somebody really needed it, they could use it).

### PR DESCRIPTION
**Pull request by neongreen**
Fixes #7

### CODE REVIEW

**Comment by neongreen** [comment]
Would you also want me to create a CHANGELOG for 0.3→0.4? (I like it when libraries have changelogs so I'm willing to spend time on it)

**Comment by neongreen** [comment]
The tests have passed.

**Comment by agrafix** [comment]
Cool, thanks!

**Comment by agrafix** [comment]
Re Changelog: Sure, sounds good 👍

**Pull request merged**
